version: '3'

services:
  dbblended:
    container_name: blended_db
    build:
      context: .
      dockerfile: Dockerfile_mariadb
    volumes:
      - blended_mariadb:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pwd_rootdb

  blended_webserver:
    depends_on:
      - dbblended
    container_name: blended_webserver
    build: .
    volumes:
      - ./app:/var/www/html
    ports:
      - "80"
    restart: always

  blended_mailserver:
    depends_on:
      - dbblended
    container_name: blended_mailserver
    build:
      context: .
      dockerfile: Dockerfile_postfix
    volumes:
      - ./app:/app
    restart: always

volumes:
  blended_mariadb:

networks:
  default:
    external:
      name: reverseproxy

